<?php

declare(strict_types=1);

namespace Eram\Daynum\Tests\Conformance;

use Eram\Daynum\Formatter\DigitTransliterator;
use Eram\Daynum\Locale\LocaleRegistry;
use Eram\Daynum\Tests\Conformance\Support\FixtureReader;
use PHPUnit\Framework\TestCase;

/**
 * Differential-tests {@see \Eram\Daynum\Locale\LocaleData::relativeTime()}
 * against `Intl.RelativeTimeFormat` (numeric: 'always') output generated by
 * tools/generate-relative-time-node.mjs.
 *
 * Locale methods return Latin digits (views transliterate later), so the
 * oracle strings are normalized with DigitTransliterator::toLatin() first.
 */
final class RelativeTimeConformanceTest extends TestCase
{
    public function testRelativeTimeMatchesIntl(): void
    {
        $fixture = __DIR__ . '/../fixtures/relative-time.jsonl.gz';
        $this->assertFileExists($fixture);

        $rows = 0;
        $mismatches = [];
        foreach (FixtureReader::rows($fixture) as $row) {
            $rows++;
            $locale = LocaleRegistry::get($row['locale']);
            if (isset($row['now'])) {
                if ($locale->relativeTimeNow() !== $row['now']) {
                    $mismatches[] = sprintf('%s now: expected "%s", got "%s"', $row['locale'], $row['now'], $locale->relativeTimeNow());
                }
                continue;
            }
            foreach (['past' => false, 'future' => true] as $key => $future) {
                $expected = DigitTransliterator::toLatin($row[$key]);
                $actual = $locale->relativeTime($row['value'], $row['unit'], $future);
                if ($actual !== $expected) {
                    $mismatches[] = sprintf(
                        '%s %s %d %s: expected "%s", got "%s"',
                        $row['locale'],
                        $row['unit'],
                        $row['value'],
                        $key,
                        $expected,
                        $actual,
                    );
                }
            }
        }

        $this->assertGreaterThan(3900, $rows, 'fixture looks truncated');
        $this->assertSame([], array_slice($mismatches, 0, 20), count($mismatches) . ' mismatches');
    }
}
