<?php

declare(strict_types=1);

// Code style: PER Coding Style 2.0, the current PHP-FIG standard.
// Check with `composer cs`, fix with `composer cs:fix`.
$finder = (new PhpCsFixer\Finder())
    ->in([__DIR__ . '/src', __DIR__ . '/tests', __DIR__ . '/tools'])
    // Generated by tools/generate-uaq-table.php; the oracle workflow diffs it.
    ->notPath('Calendar/Hijri/Table.php')
    ->append([__FILE__]);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(false)
    ->setRules([
        '@PER-CS2.0' => true,
    ])
    ->setFinder($finder);
