<?php

declare(strict_types=1);

/**
 * Diff the PHP-generated and Node-generated oracle fixtures row-by-row.
 *
 * Metadata headers differ by design (they record the generator, ICU version,
 * and timestamp) so the first line of each file is skipped. Every subsequent
 * line must match byte-for-byte; the first disagreement prints a diff and
 * exits non-zero.
 *
 * When comparing Jalali fixtures generated by different ICU versions,
 * structural detection tolerates Nowruz boundary shifts: rows where JDN,
 * Gregorian date, and day-of-week all match but the Jalali date differs.
 * This is the known Birashk/Borkowski leap-year divergence pattern between
 * ICU versions and is reported but not treated as a failure.
 *
 * Usage:
 *   php tools/verify-oracles-agree.php
 */

const FIXTURE_DIR = __DIR__ . '/../tests/fixtures';

$pairs = [
    ['gregorian.jsonl.gz',       'gregorian.node.jsonl.gz'],
    ['jalali.jsonl.gz',          'jalali.node.jsonl.gz'],
    ['hijri-civil.jsonl.gz',     'hijri-civil.node.jsonl.gz'],
    ['hijri-umalqura.jsonl.gz',  'hijri-umalqura.node.jsonl.gz'],
];

/** @return array{icuVersion: string, calendar: string} */
function parseHeader(string $headerLine): array
{
    $data = json_decode($headerLine, true);
    return [
        'icuVersion' => $data['meta']['icuVersion'] ?? 'unknown',
        'calendar'   => $data['meta']['calendar'] ?? 'unknown',
    ];
}

$overallOk = true;

foreach ($pairs as [$phpFile, $nodeFile]) {
    $phpPath  = FIXTURE_DIR . '/' . $phpFile;
    $nodePath = FIXTURE_DIR . '/' . $nodeFile;

    if (!file_exists($phpPath)) {
        fwrite(STDERR, "Missing fixture: {$phpPath} — run generate-fixtures-php.php first.\n");
        $overallOk = false;
        continue;
    }
    if (!file_exists($nodePath)) {
        fwrite(STDERR, "Missing fixture: {$nodePath} — run generate-fixtures-node.mjs first.\n");
        $overallOk = false;
        continue;
    }

    $php = gzopen($phpPath, 'r');
    $node = gzopen($nodePath, 'r');

    // Skip and record the header lines — they're expected to differ.
    $phpHeader  = trim((string) gzgets($php));
    $nodeHeader = trim((string) gzgets($node));

    fprintf(STDOUT, "Comparing %s ↔ %s\n", $phpFile, $nodeFile);
    fprintf(STDOUT, "  php header:  %s\n", $phpHeader);
    fprintf(STDOUT, "  node header: %s\n", $nodeHeader);

    $phpMeta  = parseHeader($phpHeader);
    $nodeMeta = parseHeader($nodeHeader);

    $tolerateJalali = $phpMeta['calendar'] === 'persian'
        && $phpMeta['icuVersion'] !== $nodeMeta['icuVersion'];

    if ($tolerateJalali) {
        fprintf(STDOUT, "  ⚠ ICU versions differ (%s vs %s) — tolerating known Jalali divergence windows\n",
            $phpMeta['icuVersion'], $nodeMeta['icuVersion']);
    }

    $line = 1; // the headers were line 1
    $diffs = 0;
    $skippedDivergence = 0;
    while (true) {
        $a = gzgets($php);
        $b = gzgets($node);
        $line++;

        if ($a === false && $b === false) {
            break;
        }
        if ($a === false || $b === false) {
            fprintf(STDERR, "  LENGTH MISMATCH at line %d\n", $line);
            $overallOk = false;
            break;
        }

        $aStr = trim((string) $a);
        $bStr = trim((string) $b);
        if ($aStr !== $bStr) {
            if ($tolerateJalali) {
                $phpRow  = json_decode($aStr, true);
                $nodeRow = json_decode($bStr, true);
                if (is_array($phpRow) && is_array($nodeRow)
                    && $phpRow['jdn'] === $nodeRow['jdn']
                    && $phpRow['g'] === $nodeRow['g']
                    && $phpRow['dow'] === $nodeRow['dow']
                    && $phpRow['j'] !== $nodeRow['j']) {
                    $skippedDivergence++;
                    continue;
                }
            }

            if ($diffs < 5) {
                fprintf(STDERR, "  DIFF line %d\n    php:  %s    node: %s", $line, $a, $b);
            }
            $diffs++;
            $overallOk = false;
        }
    }

    gzclose($php);
    gzclose($node);

    if ($skippedDivergence > 0) {
        fprintf(STDOUT, "  ⊘ %d rows skipped (Jalali Nowruz boundary shift)\n", $skippedDivergence);
    }
    if ($diffs === 0) {
        fprintf(STDOUT, "  ✓ fixtures agree on every row\n");
    } else {
        fprintf(STDERR, "  ✗ %d disagreeing rows\n", $diffs);
    }
}

exit($overallOk ? 0 : 1);
